config/routes.rb
DatingOverMeal::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  match '/tour' => 'tour#index', :as => :tour
  match '/dashboard' => 'dashboard#index', :as => :dashboard
  match '/help' => 'p#help'
  
  match '/users/follow' => 'users#follow'
  
  match '/webcam/capture' => 'webcam#capture', :as => :webcam_capture
  
  match '/error' => 'error#index', :as => :error
  
  resources :profiles
  
  resources :thoughts
  
  resources :messages
  
  resources :users
  
  resources :places do
    
    member do
      post :rate
      post :like
      post :visit
    end
    
  end
  
  resources :images do
    
    member do
      post :make_primary
    end
    
  end
  
  resources :appointments do
    member do
      post :report_abuse
    end
  end
  
  resources :albums do
    member do
      post :upload_photos
    end
  end
  
  resources :videos
  
  root :to => "home#index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    @thought = Thought.new
    @messages = current_user.inbox_messages.active.not_read.most_recent.limit(3)
    @random_places = Place.includes(:images, :interactions).random(8)
    @following = current_user.following.limit(5)
    @followers = current_user.followers.limit(5)
    @visited_places = current_user.visited_places.includes(:images)
    @liked_places = current_user.liked_places.includes(:images)
    @proposed_appointments = current_user.proposed_appointments
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_dating_calendar.erb
<script>
$(function(){
  $("#dating_calendar").fullCalendar({
    <% if @proposed_appointments.size > 0 %>
      events: [
        <% @proposed_appointments.each do |app| %>
          {
            title: 'Date',
            start: '<%= app.date.strftime("%Y-%m-%d") %>',
            url: '<%= appointment_path(app) %>'
          },
        <% end %>
      ],
      firstDay: 1,
      eventBackgroundColor: "#55a1d5"
    <% end %>
  })
})
</script>

app/views/dashboard/index.haml
- @title_for_layout = "Dashboard"
- @body_id = "dashboard"
- @body_class = "dashboard"

%h1.page_header= @title_for_layout

= render :partial => "shared/flash_notice"

#stage
  #left
    #picture_wrapper
      #frame
        = image_tag current_user.avatar.url(:thumb), :alt => current_user.username
      = link_to "Edit profile", edit_profile_path(current_user), :class => "button white"
  
  #right
  
    .box#calendar
      %h2.header Your dating calendar
      .content
        .embossed_box#dating_calendar_wrapper
          #dating_calendar
  
    .box#thoughts
      %h2.header What's on your mind?
      .content
        .embossed_box
          = form_for @thought, :remote => true do |f|
            = f.text_area :description, :class => :textbox, :id => :thoughts_box
            = f.submit :value => "Share", :class => :action_button, :id => "share_thought"
          
    .box
      %h2.header Places you might like
      .content
        %ul.places_listing
          - @random_places.each do |place|
            %li.clearfix.white.place
              = link_to place_path(place) do
                - primary_image_url = place.primary_image
                - if primary_image_url.nil?
                  = image_tag "restaurant_silhouette.png", :class => :place_photo
                - else
                  = image_tag primary_image_url, :class => :place_photo
              .place_overview
                %h3.place_name
                  = link_to place.name, place_path(place)
                .place_short_description
                  %p= truncate(place.description, :length => 100)
                .place_location #{place.city}, #{place.state}
              .place_other_info
                .clearfix.ratings= place.rating_average
                .comments
                  %span= place.count_likes 
                  %span.caption likes

                .visits
                  %span= place.count_visits
                  %span.caption visits
          
        = link_to "View all places", places_path, :class => :action_button
                  
    .box#inbox_messages
      %h2.header Messages (#{@messages.count})
      .content
        - if @messages.count == 0
          You have no new messages
        - else
          = render :partial => "shared/messages_list", :locals => {:show_profile_link => false}
              
          = link_to "View All Messages", messages_path, :class => :action_button
        
    .box#followed
      %h2.header Following
      .content
        - if @following.size > 0
          = render :partial => "shared/users_list", :locals => {:users => @following}
        - else
          %p You're not following anybody
      
    .box#followers
      %h2.header Followers
      .content
        - if @followers.size > 0
          = render :partial => "shared/users_list", :locals => {:users => @followers}
        - else
          %p You don't have any followers
        
    .box#places_you_been
      %h2.header Places you've been to
      .content
        - if @visited_places.size > 0
          = render :partial => "shared/places_list", :locals => {:places => @visited_places}
        - else
          %p You haven't been to any places yet
        = link_to "Check out other places", places_path, :class => :action_button
        
    .box#places_you_like
      %h2.header Places you like
      .content
        - if @liked_places.size > 0
          = render :partial => "shared/places_list", :locals => {:places => @liked_places}
        - else
          %p You don't have any favorite places yet
        = link_to "Check out other places", places_path, :class => :action_button
      
  .clearfloat
  
= render 'dating_calendar'