config/routes.rb
DatingOverMeal::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  match '/tour' => 'tour#index', :as => :tour
  match '/dashboard' => 'dashboard#index', :as => :dashboard
  match '/help' => 'p#help'
  
  match '/users/follow' => 'users#follow'
  
  match '/webcam/capture' => 'webcam#capture', :as => :webcam_capture
  
  match '/error' => 'error#index', :as => :error
  
  resources :profiles
  
  resources :thoughts
  
  resources :messages
  
  resources :users
  
  resources :places do
    
    member do
      post :rate
      post :like
      post :visit
    end
    
  end
  
  resources :images do
    
    member do
      post :make_primary
    end
    
  end
  
  resources :appointments do
    member do
      post :report_abuse
    end
  end
  
  resources :albums do
    member do
      post :upload_photos
    end
  end
  
  resources :videos
  
  root :to => "home#index"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  belongs_to :user
  
  # Used on the users listing (index) page
  def brief
    b = []
    
    age = calculate_age
    
    b << age unless age.nil?
    
    b << self.gender unless self.gender.nil?
    
    b << self.zodiac unless self.zodiac.nil?
    
    b.join(" - ")
  end
  
  def calculate_age
    if self.birth_year.blank? or self.birth_month.blank? or self.birth_day.blank?
      nil
    else
      now = Time.now
      age = now.year - self.birth_year
      age -= 1 if Time.mktime(now.year, self.birth_month, self.birth_day) > Time.mktime(now.year, now.month, now.day)
      age
    end
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  #before_filter :authenticate_user!, :only => :update
  
  def show
    begin
      @user = User.find_by_username(params[:id])
      @profile = @user.profile
      @recent_activities = @user.recent_activities
      @recent_thoughts = @user.recent_thoughts
      @visited_places = @user.visited_places
      @liked_places = @user.liked_places
      @albums = @user.albums.includes(:images)
    rescue
      flash[:error] = "The profile you're looking for does not exist"
      redirect_to error_path
    end
  end
  
  def edit
    @heights = []
    (4..6).each do |f|
      (0..11).each do |r|
        @heights << "#{f}' #{r}\""
      end
    end
    @heights << "Rather not say"
    @profile = Profile.find(params[:id])
  end
  
  def update
    @profile.update_attributes(params[:profile])
    render :json => {:success => 1}
  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def hours_passed(from)
    (Time.now.to_i - from.to_i) / (24*60*60)
  end
end

app/views/profiles/edit.haml
- @title_for_layout = "Edit profile"
- @body_id = "profile"
- @body_class = "profile"

%h1.page_header= @title_for_layout

#stage
  #left
    #picture_wrapper
      #frame
        = image_tag current_user.avatar.url(:thumb), :alt => current_user.username
      = link_to "Change picture", edit_user_path(current_user), :class => "button white"
        
    = link_to "View Profile", profile_path(current_user.username), :class => "button white social_option"
      
  #right
    = form_for @profile, :remote => true, :html => {:class => :zigzag_form} do |f|
      .box#profile_information
        %h2.header Basic personal information
        .content
          .form_row.clearfix
            = f.label :firstname, "First name"
            = f.text_field :firstname, :class => :textbox
          
          .form_row.clearfix
            = f.label :lastname, "Last name"
            = f.text_field :lastname, :class => :textbox
          
          .form_row.clearfix
            = f.label :gender
            = f.select :gender, options_for_select(["male", "female", "Rather not say"], @profile.gender), :include_blank => "-- no answer --"
          
          .form_row.clearfix
            %label Birthday
            = f.select :birth_month, options_for_select(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"], @profile.birth_month), :include_blank => "-- no answer --"
            = f.select :birth_day, options_for_select(1..31, @profile.birth_day.to_i), :include_blank => "-- no answer --"
            = f.select :birth_year, options_for_select(1993.downto(1905), @profile.birth_year.to_i), :include_blank => "-- no answer --"
        
          .form_row.clearfix
            = f.label :relationship_status
            = f.select :relationship_status, options_for_select(["Single", "It's complicated", "In an open relationship", "Widowed", "Seperated", "Divorced", "Rather not say"], @profile.relationship_status), :include_blank => "-- no answer --"
        
          .form_row.clearfix
            = f.label :city
            = f.text_field :city, :class => :textbox
          
          .form_row.clearfix
            = f.label :state
            = f.text_field :state, :class => :textbox
          
          .form_row.clearfix
            = f.label :country
            = f.select :country, options_for_select(Carmen.countries, @profile.country), :include_blank => "-- no answer --"
            
          .form_row.clearfix
            = f.label :zipcode
            = f.text_field :zipcode, :class => :textbox
          
          .form_row.clearfix
            = f.label :occupation
            = f.text_field :occupation, :class => :textbox
          
          .form_row.clearfix
            = f.label :school
            = f.text_field :school, :class => :textbox
          
          .form_row.clearfix
            = f.label :company
            = f.text_field :company, :class => :textbox
          
          .form_row.clearfix
            = f.label :website
            = f.text_field :website, :class => :textbox
          
          .form_row.clearfix
            = f.label :facebook
            = f.text_field :facebook, :class => :textbox
          
          .form_row.clearfix
            = f.label :twitter
            = f.text_field :twitter, :class => :textbox
          
          .form_row.clearfix
            = f.label :flickr
            = f.text_field :flickr, :class => :textbox
         
          .form_row.clearfix
            = f.label :linkedin
            = f.text_field :linkedin, :class => :textbox
        
      #about_you.box
        %h2.header About you
        .content
          .form_row.clearfix
            = f.label :description, "About me"
            = f.text_area :description, :class => :textbox
        
          .form_row.clearfix
            = f.label :languages
            = f.text_area :languages, :class => :textbox
        
          .form_row.clearfix
            = f.label :hobbies
            = f.text_area :hobbies, :class => :textbox
          
          .form_row.clearfix
            = f.label :most_attractive_feature
            = f.select :most_attractive_feature, options_for_select(["Eyes", "Face", "Smile", "Breast", "Hands", "Legs", "Shoulder", "Hair", "Abs", "Rather not say"], @profile.most_attractive_feature), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :ethnicity
            = f.select :ethnicity, options_for_select(["Asian", "Black", "Hispanic/Latin", "White", "Middle Eastern", "Native American", "Mixed", "Rather not say"], @profile.ethnicity), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :height
            = f.select :height, options_for_select(@heights, @profile.height), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :body_type
            = f.select :body_type, options_for_select(["Large", "Slim/Slender", "Muscular", "Curvy", "Athletic", "A few extra pounds", "Rather not say"], @profile.body_type), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :hair_color
            = f.select :hair_color, options_for_select(["Black", "Blone", "Brown", "Red", "Salt and Pepper", "White", "Grey", "Rather not say"], @profile.hair_color), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :eye_color
            = f.select :eye_color, options_for_select(["Black", "Blue", "Green", "Hazel", "Brown", "Rather not say"], @profile.eye_color), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :tattoos
            = f.select :tattoos, options_for_select(["None, absolutely not", "None, but I might get one", "Many tattoos", "Rather not say"], @profile.tattoos), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :piercings
            = f.select :piercings, options_for_select(["None, absolutely not", "None, but I might get one", "Many piercings", "Rather not say"], @profile.piercings), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :zodiac
            = f.select :zodiac, options_for_select(["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces", "Rather not say"], @profile.zodiac), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :religion
            = f.select :religion, options_for_select(["Atheist", "Buddhist / Taoist", "Christian", "Hindu", "Jewish", "Mormon", "Muslim / Islam", "Scientology", "Rather not say"], @profile.religion), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :exercise
            = f.select :exercise, options_for_select(["Never", "1-2 times per week", "3-4 times per week", "5 or more times per week", "Rather not say"], @profile.exercise), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :smoking
            = f.select :smoking, options_for_select(["Never", "Sometimes", "Occasionally", "Everyday", "Rather not say"], @profile.smoking), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :drinking
            = f.select :drinking, options_for_select(["Never", "Sometimes", "Occasionally", "I'm a lush", "Rather not say"], @profile.drinking), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :kids
            = f.select :kids, options_for_select(["No kids", "Has 1 child", "Has children", "Like kids", "Don't like kids", "Doesn't want kids", "Rather not say"], @profile.kids), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :pets
            = f.select :pets, options_for_select(["Has pet(s)", "No pets", "Like pets", "Don't like pets", "Rather not say"], @profile.pets), :include_blank => "- no answer -"
          
      .box#what_you_looking_for
        %h2.header What you're looking for
        .content
          .form_row.clearfix
            = f.label :looking_for_gender, "Gender"
            = f.select :looking_for_gender, options_for_select(["Man", "Woman", "Rather not say"], @profile.looking_for_gender), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :looking_for_age_min, "No younger than"
            = f.select :looking_for_age_min, options_for_select((18..70).to_a, @profile.looking_for_age_min), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :looking_for_age_max, "No older than"
            = f.select :looking_for_age_max, options_for_select((18..70).to_a, @profile.looking_for_age_max), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :looking_for_ethnicity, "Ethnicity"
            = f.select :looking_for_ethnicity, options_for_select(["Asian", "Black", "Hispanic/Latin", "White", "Middle Eastern", "Native American", "Mixed", "Rather not say"], @profile.looking_for_ethnicity), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :looking_for_body_type, "Body type"
            = f.select :looking_for_body_type, options_for_select(["Large", "Slim/Slender", "Muscular", "Curvy", "Athletic", "Rather not say"], @profile.looking_for_body_type), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :looking_for_location, "Location"
            = f.select :looking_for_location, options_for_select(["Near me", "Anywhere"], @profile.looking_for_location), :include_blank => "- no answer -"
          
          .form_row.clearfix
            = f.label :partner_expectation, "What are you looking for in a partner"
            = f.text_area :partner_expectation, :class => :textbox
      
      .button_container
        = f.submit :value => "Update", :class => :action_button, :id => :update_profile
  
  .clearfloat

app/views/profiles/show.haml
- @title_for_layout = "#{@profile.firstname} #{@profile.lastname}"
- @body_id = "profile"
- @body_class = "profile"

#profile_top_wash.clearfix.page_header
  #profile_header_left
    %h1#profile_name_header= @title_for_layout
  
    - hours_passed_since_last_logged_in = hours_passed(@user.last_sign_in_at)

    %p
      %b Last login:
      - if hours_passed_since_last_logged_in == 0
        just a little while ago
      - else
        #{hours_passed_since_last_logged_in} hours ago

#stage
  #left
    #picture_wrapper
      #frame
        = image_tag @user.avatar.url(:thumb), :alt => @user.username
    
      - if user_signed_in? and current_user.id == @user.id
        = link_to "Edit Profile", edit_profile_path(@profile), :class => "button white", :id => :edit_my_profile
    
    - unless @profile.facebook.blank? and @profile.twitter.blank? and @profile.flickr.blank? and @profile.linkedin.blank?
      #profile_social_networks.embossed_box
        - unless @profile.facebook.blank?
          %a{:href => @profile.facebook, :target => "_blank"}
            = image_tag "facebook_16.png", :alt => :Facebook
        
        - unless @profile.twitter.blank?
          %a{:href => @profile.facebook, :target => "_blank"}
            = image_tag "twitter_16.png", :alt => :Twitter
        
        - unless @profile.flickr.blank?
          %a{:href => @profile.flickr, :target => "_blank"}
            = image_tag "flickr_16.png", :alt => :Flickr
        
        - unless @profile.linkedin.blank?
          %a{:href => @profile.linkedin, :target => "_blank"}
            = image_tag "linkedin_16.png", :alt => :Linkedin
    
    #follows_count_wrapper.embossed_box
      %ul#follows_count.clearfix
        %li
          %span Following
          %p.count= @user.following.count
        
        %li 
          %span Followers
          %p.count= @user.followers.count
    
    - if user_signed_in?  
      - unless current_user.id == @user.id
        - unless current_user.following?(@user)
          %span{:id => :follow_user, :class => "button white social_option", :followed_id => @user.id} Follow this user
        - else
          %span{:id => :following_indicator, :class => "button green social_option", :followed_id => @user.id} Following
    
    - if user_signed_in?    
      - unless current_user.id == @user.id
        %span{:id => :direct_message, :class => "button white social_option", :receiver_id => @user.id} Message this user
        
  #right
    .box#profile_details
      %h2.header 
        My profile
      .content
        .tabs_wrapper
          %ul.tabs.clearfix
            %li.current{:tab => :overview} Overview
            %li{:tab => :about} About me
            %li{:tab => :looking_for} What I'm looking for
          
        #overview.tab_content
          - unless @profile.description.blank?
            .embossed_box
              %p
                = image_tag "quote_16.png", :class => :profile_illustration
                = @profile.description
        
          
          %ul.profile_details.embossed_box
            - location = []
            - location << @profile.city unless @profile.city.blank?
            - location << @profile.state unless @profile.state.blank?
            - unless location.join(", ").blank?
              %li
                = image_tag "location_16.png", :class => :profile_illustration
                %b Location: 
                #{location.join(", ")}
            %li
              = image_tag "phone_16.png", :class => :profile_illustration
              %b Phone Number: 
              #{@profile.phone_number.blank? ? "Not specified" : @profile.phone_number}
      
            - unless @profile.birth_day.blank? or @profile.birth_month.blank? or @profile.birth_year.blank?
              %li
                = image_tag "cake_16.png", :class => :profile_illustration
                %b Birthday: 
                #{@profile.birth_month} #{@profile.birth_day}, #{@profile.birth_year}
          
            %li
              = image_tag "heart_16.png", :class => :profile_illustration
              %b Relationship status:
              #{@profile.relationship_status.blank? ? "Not specified" : @profile.relationship_status}
          
            %li
              = image_tag "job_16.png", :class => :profile_illustration
              %b Occupation: 
              #{@profile.occupation.blank? ? "Not specified" : @profile.occupation}
        
            - unless @profile.school.blank?
              %li
                = image_tag "school_16.png", :class => :profile_illustration
                %b School: 
                #{@profile.school.blank? ? "Not specified" : @profile.school}
          
            %li
              = image_tag "company_16.png", :class => :profile_illustration
              %b Company: 
              #{@profile.company.blank? ? "Not specified" : @profile.company}
        
            %li
              = image_tag "language_16.png", :class => :profile_illustration
              %b Languages: 
              #{@profile.languages.blank? ? "Not specified" : @profile.languages}
            
            %li.last
              = image_tag "basketball_16.png", :class => :profile_illustration
              %b Hobbies: 
              #{@profile.hobbies.blank? ? "Not specified" : @profile.hobbies}
              
        #about.tab_content{:style => "display:none"}
          .embossed_box
            %ul.profile_details
              %li
                %b Most attractive feature:
                = @profile.most_attractive_feature.blank? ? "Not specified" : @profile.most_attractive_feature
              %li
                %b Ethnicity:
                = @profile.ethnicity.blank? ? "Not specified" : @profile.ethnicity
              %li
                %b Height:
                = @profile.height.blank? ? "Not specified" : @profile.height
              %li
                %b Body type:
                = @profile.body_type.blank? ? "Not specified" : @profile.body_type
              %li
                %b Hair color:
                = @profile.hair_color.blank? ? "Not specified" : @profile.hair_color
              %li
                %b Eye color:
                = @profile.eye_color.blank? ? "Not specified" : @profile.eye_color
              %li
                %b Tattoos:
                = @profile.tattoos.blank? ? "Not specified" : @profile.tattoos
              %li
                %b Piercings:
                = @profile.piercings.blank? ? "Not specified" : @profile.piercings
              %li
                %b Zodiac sign:
                = @profile.zodiac.blank? ? "Not specified" : @profile.zodiac
              %li
                %b Religion:
                = @profile.religion.blank? ? "Not specified" : @profile.religion
              %li
                %b Exercise:
                = @profile.exercise.blank? ? "Not specified" : @profile.exercise
              %li
                %b Smoking:
                = @profile.smoking.blank? ? "Not specified" : @profile.smoking
              %li
                %b Drinking:
                = @profile.drinking.blank? ? "Not specified" : @profile.drinking
              %li
                %b Kids:
                = @profile.kids.blank? ? "Not specified" : @profile.kids
              %li.last
                %b Pets:
                = @profile.pets.blank? ? "Not specified" : @profile.pets
              
        #looking_for.tab_content{:style => "display:none"}
          .embossed_box
            %ul.profile_details
              %li
                %b Gender:
                = @profile.looking_for_gender.blank? ? "Not specified" : @profile.looking_for_gender
              %li
                %b No younger than:
                = @profile.looking_for_age_min.blank? ? "Not specified" : @profile.looking_for_age_min
              %li
                %b No older than:
                = @profile.looking_for_age_max.blank? ? "Not specified" : @profile.looking_for_age_max
              %li
                %b Ethnicity:
                = @profile.looking_for_ethnicity.blank? ? "Not specified" : @profile.looking_for_ethnicity
              %li
                %b Body type:
                = @profile.looking_for_body_type.blank? ? "Not specified" : @profile.looking_for_body_type
              %li.last
                %b Location:
                = @profile.looking_for_location.blank? ? "Not specified" : @profile.looking_for_location
              
          - unless @profile.partner_expectation.blank?
            .embossed_box
              %p 
                = image_tag "star_16.png", :class => :profile_illustration
                In my ideal world, a great partner is one that
              %pre.form_row= @profile.partner_expectation
              
          
    .box#thoughts
      %h2.header What's on my mind
      .content
        - if @recent_thoughts.size > 0
          %ul
            - @recent_thoughts.each do |thought|
              %li= thought.description
        - else
          %p #{@profile.firstname} has not shared any thought yet
          
    .box#profile_recent_activities
      %h2.header Recent activity
      .content
        %ul
          - @recent_activities.each do |activity|
            %li #{activity.activity_description} - #{activity.created_at.strftime("%b %d, %Y")}
            
    .box#profile_albums
      %h2.header Photos
      .content
        - if @albums.length > 0
          = render :partial => "shared/albums_listing", :locals => {:albums => @albums}
        - else
          #{@profile.firstname} doesn't have any album
          
    .box
      %h2.header Places I've visited
      .content
        - if @visited_places.size > 0
          = render :partial => "shared/places_list", :locals => {:places => @visited_places}
        - else
          %p #{@profile.firstname} has not visited any places yet
      
  
  .clearfloat
  
- if user_signed_in?
  - @message = Message.new
  #pop_dialog.pop_dialog{:style => "display:none"}
    %h2.header 
      New message
    .content
      = form_for @message, :remote => true do |f|
        .form_row
          = f.label :subject
          = f.text_field :subject, :class => :textbox
        .form_row
          = f.label :content
          = f.text_area :content, :class => :textbox
        = f.hidden_field :receiver_id, :value => @user.id
        = f.hidden_field :sender_id, :value => current_user.id
        .button_container
      
          = f.submit :value => "Send", :class => :action_button
        
          %input{:type => :button, :class => "remorse_button cancel_pop_dialog", :value => "Cancel", :id => "cancel_message"}