config/routes.rb
DatingOverMeal::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  match '/tour' => 'tour#index', :as => :tour
  match '/dashboard' => 'dashboard#index', :as => :dashboard
  match '/help' => 'p#help'
  
  match '/users/follow' => 'users#follow'
  
  match '/webcam/capture' => 'webcam#capture', :as => :webcam_capture
  
  match '/error' => 'error#index', :as => :error
  
  resources :profiles
  
  resources :thoughts
  
  resources :messages
  
  resources :users
  
  resources :places do
    
    member do
      post :rate
      post :like
      post :visit
    end
    
  end
  
  resources :images do
    
    member do
      post :make_primary
    end
    
  end
  
  resources :appointments do
    member do
      post :report_abuse
    end
  end
  
  resources :albums do
    member do
      post :upload_photos
    end
  end
  
  resources :videos
  
  root :to => "home#index"

end

app/views/shared/_albums_listing.haml
%ul.albums_listing.clearfix
  - albums.each do |album|
    %li
      = link_to album_path(album) do
        - if album.images.size == 0
          = image_tag "album_sil.jpg", :class => :album
        - else
          = image_tag album.images.first.picture.url(:thumb), :class => :album
          
      .name 
        = album.title
      - num_photos = album.images.length
      .photos_count 
        (#{pluralize(num_photos, "photo")})

app/views/shared/_devise_form_logo.haml
%h2
  = link_to root_path do
    = image_tag "logo.png", :alt => @title_for_layout, :id => :logo

app/views/shared/_flash_alert.haml
- if flash[:alert]
  .alert-message
    .error
      = flash[:alert]

app/views/shared/_flash_notice.haml
- if flash[:notice]
  .alert-message
    .success
      = flash[:notice]

app/views/shared/_footer.haml
%footer#footer
  #footer_content.clearfix
    = image_tag "dom_logo_small.png", :id => :footer_logo
    #copyright_statement
      %p
        &copy; 2011 Dating over Meal. All rights reserved.
        %br
        Dating over Meal is open-sourced on Github and welcomes all forks and pull requests
    #social_presence
      = image_tag "twitter.png"
      = image_tag "facebook.png"

app/views/shared/_form_errors.haml
- unless target.errors.empty?
  .alert-message.error
    = f.error_messages :header_message => nil, :message => ""

app/views/shared/_header.haml
%header#auth_header
  #middle_section
    #logo
      = link_to root_path do
        = image_tag "logo.png"
  
    - if user_signed_in?
      #nav
        %ul
          %li
            = link_to profile_path(current_user.username) do
              = image_tag current_user.avatar(:thumb), :id => :nav_profile_photo, :alt => current_user.username
              %span= current_user.username.truncate(8)
            
            .leaf_menu_wrapper  
              .leaf_menu
                = link_to "Profile", profile_path(current_user.username)
                = link_to "Edit Profile", edit_profile_path(current_user.profile)
                = link_to "Logout", destroy_user_session_path, :method => :delete
                %a{:style => "border-bottom:0"} Account Settings
          
          %li{:class => @body_class == "dashboard" ? "current" : ""}
            = link_to dashboard_path do
              = image_tag "dash_24.png"
              %span Dashboard
          
          %li{:class => @body_class == "places" ? "current" : ""}
            = link_to places_path do
              = image_tag "place_24.png"
              %span Places
          
          %li{:class => @body_class == "users" ? "current" : ""}
            = link_to users_path do
              = image_tag "members_24.png"
              %span Members
          
          %li{:class => @body_class == "messages" ? "current" : ""}
            = link_to messages_path do
              = image_tag "message_24.png"
              %span Message
          
          %li{:class => @body_class == "albums" ? "current" : ""}
            = link_to albums_path do
              = image_tag "album_24.png"
              %span Albums
              
          %li{:class => @body_class == "videos" ? "current" : ""}
            = link_to videos_path do
              = image_tag "video_24.png"
              %span Videos

app/views/shared/_messages_list.haml
- if @messages.size > 0
  %ul.messages_list
    - @messages.each do |message|
      - sender = message.sender
      - profile = sender.profile
      %li.clearfix.white
        = link_to message_path(message), :class => :show_message_details do
          = image_tag sender.avatar.url(:thumb), :class => :profile_photo, :alt => sender.username
          %span.snap
            - if show_profile_link
              %b.author
                = link_to profile.firstname.to_s + " " + profile.lastname.to_s, profile_path(sender.username)
            - else
              %b.author #{profile.firstname} #{profile.lastname}
            %span.preview= truncate(message.content, :length => 100)
    
        = link_to "x", message_path(message), :method => :delete, :class => :delete, :confirm => "Are you sure?"
- else
  %p You don't have any messages yet

app/views/shared/_overlay_and_alert.haml
#overlay{:style => "display:none"}

#alert{:style => "display:none", :class => :yellow}
  .content#alert_content

#error{:style => "display:none", :class => :red}
  .content#error_content

app/views/shared/_places_list.haml
%ul.places_list.clearfix
  - places.each do |place|
    %li
      = link_to place_path(place) do
        - if place.primary_image.nil?  
          = image_tag "restaurant_silhouette.png", :class => :place, :title => place.name
        - else
          = image_tag place.primary_image, :class => :place, :title => place.name

app/views/shared/_profile_picture.haml
#picture_wrapper
  #frame
    = image_tag current_user.avatar.url(:thumb), :alt => current_user.username

app/views/shared/_users_list.haml
%ul.follow_list.clearfix
  - users.each do |user|
    %li
      = link_to profile_path(user.username) do
        = image_tag user.avatar.url(:thumb), :class => :profile_photo, :alt => user.username