config/routes.rb
DatingOverMeal::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  match '/tour' => 'tour#index', :as => :tour
  match '/dashboard' => 'dashboard#index', :as => :dashboard
  match '/help' => 'p#help'
  
  match '/users/follow' => 'users#follow'
  
  match '/webcam/capture' => 'webcam#capture', :as => :webcam_capture
  
  match '/error' => 'error#index', :as => :error
  
  resources :profiles
  
  resources :thoughts
  
  resources :messages
  
  resources :users
  
  resources :places do
    
    member do
      post :rate
      post :like
      post :visit
    end
    
  end
  
  resources :images do
    
    member do
      post :make_primary
    end
    
  end
  
  resources :appointments do
    member do
      post :report_abuse
    end
  end
  
  resources :albums do
    member do
      post :upload_photos
    end
  end
  
  resources :videos
  
  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  
  has_many :images, :as => :imageable, :dependent => :destroy
  
  validates_presence_of :title
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  before_filter :authenticate_user!, :only => [:new, :edit, :destroy]
  before_filter :find_album, :only => [:edit, :update, :upload_photos, :show, :destroy]
  before_filter :manipulatable?, :only => [:edit, :destroy]
  
  def index
    @albums = current_user.albums.includes(:images)
  end
  
  def new
    @album = Album.new
  end
  
  def create
    @album = Album.new(params[:album])
    @album.user_id = current_user.id
    
    if @album.save
      flash[:notice] = "Your album has been created"
      redirect_to :action => :index
    else
      render :action => :new
    end
  end
  
  def edit
  end
  
  def update
    if @album.update_attributes(params[:album])
      render :json => {:success => -1, :message => "Album has been updated"}
    else
      render :json => {:success => 1, :message => "An error occured. Album was not updated"}
    end
  end
  
  def show
    @images = @album.images
  end
  
  def destroy
    @album.destroy
    flash[:notice] = "Your album has been deleted"
    redirect_to :action => :index
  end
  
  def upload_photos
    image = Image.new(coerce(params))
    
    if image.save
      @album.images << image
      
      render :json => {:succcess => 1}
    else
      render :json => {:succcess => -1}
    end
  end
  
  private
  
  def coerce(params)
    h = Hash.new
    h[:picture] = params[:Filedata]
    h[:picture].content_type = MIME::Types.type_for(h[:picture].original_filename).to_s.gsub("[", "").gsub("]", "")
    h
  end
  
  def find_album
    @album = Album.find(params[:id])
  end
  
  def manipulatable?
    unless @album.user_id == current_user.id
      redirect_to :action => :index
    end
  end
  
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.haml
- @title_for_layout = "Edit album \"#{@album.title}\""
- @body_id = "my_albums"
- @body_class = "albums"

%h1.page_header= @title_for_layout

= form_for @album, :html => {:class => :zigzag_form}, :remote => true do |f|
  #stage
    #left
      %h3 Notice
      %br
      Please use JPG, GIF, or PNG and limit file size to 2MB
  
    #right
      
      .box
        %h2.header Album info
        .content
          .form_row
            = f.label :title
            = f.text_field :title, :class => :textbox
      
          .form_row
            = f.label :description
            = f.text_area :description, :class => :textbox
        
          .form_row
            = f.label :location
            = f.text_field :location, :class => :textbox
        
          .form_row
            %label
            = f.submit :value => "Update", :class => :action_button
      
      .box      
        %h2.header Photos
        .content
          %input{:type => :file, :id => :file_upload}

- session_key = Rails.application.config.session_options[:key]
  
:javascript
  $(function(){
  
    $("#file_upload").uploadify({
      uploader: '/uploadify.swf',
      wmode: 'transparent',
      buttonText: 'Select photos',
      auto: true,
      multi: true,
      script: '#{upload_photos_album_path(@album)}',
      scriptData: {
        '#{Rails.application.config.session_options[:key]}': '#{cookies[session_key]}',
        '#{request_forgery_protection_token}': '#{form_authenticity_token}'
      },
      onOpen: function() {
        window.flash_alert("Your images are being uploaded. This might take a few moments");
      },
      onAllComplete: function() {
        window.flash_alert("All your images have been completed uploaded");
        window.location.href = '#{album_path(@album)}';
      }
      
    })
  })
  
- content_for :head do
  - stylesheet_link_tag "uploadify.css"

app/views/albums/index.haml
- @title_for_layout = "My albums"
- @body_id = "my_albums"
- @body_class = "albums"

%h1.page_header= @title_for_layout

= render :partial => "shared/flash_notice"

#stage
  #left
  
  #right
  
    .box
      %h2.header Albums
      .content
        = render :partial => "shared/albums_listing", :locals => {:albums => @albums}
  
    = link_to "Create new album", new_album_path, :class => :action_button
  
  .clearfloat

app/views/albums/new.haml
- @title_for_layout = "Create album"
- @body_id = "new_album"
- @body_class = "albums"

%h1.page_header= @title_for_layout

= form_for @album, :html => {:class => :zigzag_form} do |f|

  = render :partial => "shared/form_errors", :locals => {:f => f, :target => @album}

  #stage
    #left
  
    #right
      .box
        %h2.header New album
        .content
          .form_row
            = f.label :title
            = f.text_field :title, :class => :textbox
        
          .form_row
            = f.label :location
            = f.text_field :location, :class => :textbox
        
          .form_row
            = f.label :description
            = f.text_area :description, :class => :textbox
          
          .form_row
            %label
            = f.submit :value => "I'm set. Let's rock and roll", :class => :action_button
        
    .clearfloat

app/views/albums/show.haml
- @title_for_layout = "#{@album.title}"
- @body_id = "my_albums"
- @body_class = "albums"

%h1.page_header= @title_for_layout

#stage
  #left
  #right
    .box
      %h2.header Photos
      .content
        - if user_signed_in? and current_user.id = @album.user_id
          %div{:style => "margin-bottom:15px; text-align:right"}
            = link_to "Edit this album", edit_album_path(@album), :class => :action_button, :id => :edit_album
            &nbsp;&nbsp;
            = link_to "Delete this album", album_path(@album), :class => :remorse_button, :method => :delete, :confirm => "Are you sure? All your photos will be deleted."
          
        .embossed_box
          - if @images.length > 0
            %ul.photos_listing.clearfix
              - @images.each do |image|
                %li
                  %a{:href => image.picture.url, :class => :fancybox, :title => image.description, :image_id => image.id}= image_tag image.picture.url(:thumb)
          - else
            %p This album does not have any images
  
  .clearfloat